#!/usr/bin/env python
"""clancy

Usage:
    clancy create [--user <user> --server <server> --cacert <cacert_path>]
    clancy delegate --time <time> --uses <uses> [--user <user> --server <server> --cacert <cacert_path>]
    clancy encrypt --owners <owners> --min <minimum> (--str <string> | --file <path>) [--user <user> --server <server> --cacert <cacert_path>]
    clancy decrypt (--str <string> | --file <path>) [--user <user> --server <server> --cacert <cacert_path>]
    clancy summary [--user <user> --server <server> --cacert <cacert_path>]
    clancy change-password [--user <user> --server <server> --cacert <cacert_path>]
    clancy modify --action <action> --target <target> [--user <user> --server <server> --cacert <cacert_path>]
    clancy base64-encode

    clancy --help
    clancy --version

Commands:
    create:           Create a new vault.
    delegate:         Delegate your password to the server for a fixed time and number
                      of decryptions.
    encrypt:          Allows an admin user to encrypt a piece of data.
    decrypt:          Allows an admin to decrypt a piece of data.
    summary:          Provides a list of users with keys on the system.
    change-password:  Change your password.
    modify:           Modify the state of another user.
    base64-encode     Returns a base64 encoded string for upload to Red October.

Options:
    --time <time>      Delegation time string. Use Go duration string format. Ex: "2h30m"
    --uses <uses>      Delegation usages. Must be an integer.

    --action <action>  Preform action on target. One of: revoke, admin, delete.
    --target <target>  User to modify.

    --owners <owners>  Comma separated list of owners.
    --min <minimum>    Minimum delegations required to decrypt data. Must be an integer.
    --str <string>     Base64 encoded string.
    --file <path>      Path to a file of base64 encoded data.

    --user <user>      User to log in as. Defaults to current user.
    --server <server>  Red October server.
    --cacert <cacert>  Absolute path to CA cert.


    -h, --help         Show this help message and exit.
    -v, --version      Show version and exit.
"""
VERSION = '0.0.1'

from socket import timeout as socket_timeout
import os
import sys
import getpass
import json
from docopt import docopt
import requests


def abort(errstr):
    sys.stderr.write('ERROR: {}\n'.format(errstr))
    sys.exit(1)


def goodquit(exitstr):
    sys.stdout.write('{}\n'.format(exitstr))
    sys.exit()


def goodquit_json(jsondata):
    exitstr = json.dumps(jsondata, indent=2, sort_keys=True)
    sys.stdout.write('\nServer Response\n---------------\n')
    sys.stdout.write('{}\n\n'.format(exitstr))
    sys.exit()


def authenticate(username):
    try:
        sys.stdout.write('\nEnter password\n--------------\n')
        sys.stdout.write('User: {}\n'.format(username))
        password = getpass.getpass()
    except getpass.GetPassWarning:
        abort('Password may be echoed. GTFO.')
        sys.exit(1)
    return password


def load_args():
    config = {}
    locations = [os.curdir, os.path.expanduser("~/.clancy"), "/etc/clancy"]
    for loc in locations:
        try:
            with open(os.path.join(loc, "clancy.conf"), 'rb') as source:
                config = json.load(source)
                break
        except IOError:
            pass
        except ValueError:
            abort('Config file not valid json.')
    return config


def api_call(endpoint, params, payload):
    headers = {'content-type': 'application/json'}
    url = 'https://{}/{}'.format(params['--server'], endpoint)
    attempt = 0
    resp = None
    while True:
        try:
            attempt += 1
            resp = requests.post(
                url, data=payload, headers=headers, verify=args['--cacert']
            )
            resp.raise_for_status()
            break
        except (socket_timeout,
                requests.Timeout,
                requests.ConnectionError,
                requests.URLRequired) as ex:
            abort('{}'.format(ex))
        except requests.HTTPError as ex:
            sys.stderr.write('HTTP {}'.format(ex))
            if attempt >= 3:
                abort('Too many HTTP errors.')
    if resp is not None:
        try:
            return resp.json()
        except ValueError:
            abort('unexpected response from server')
    else:
        abort('post error')


if __name__ == '__main__':
    try:
        # cli params > config file
        cli_args = docopt(__doc__, version=VERSION)
        conf_args = load_args()
        args = dict(conf_args.items() + cli_args.items())

        # b64 command doesn't care about anything.
        if args['base64-encode']:
            raw_str = getpass.getpass('String to encode: ')
            b64_str = None
            try:
                b64_str = raw_str.encode('base64')
            except TypeError:
                abort('invalid string')
            goodquit('{}'.format(b64_str))

        # sanitize args
        if cli_args['--user'] is None:
            if '--user' in conf_args:
                args['--user'] = conf_args['--user']
            else:
                args['--user'] = getpass.getuser()

        for key in ['--cacert', '--server']:
            if cli_args[key] is None:
                if key in conf_args:
                    args[key] = conf_args[key]
                else:
                    abort('{} not defined. Pass in as parameter or '
                          'define in config file. See READEME for '
                          'details.'.format(key))

        for key in ['--cacert', '--file']:
            if args[key] is not None:
                if not os.path.isfile(args[key]):
                    abort('file {} not found.'.format(args[key]))

        for key in ['--min', '--uses']:
            if args[key] is not None:
                try:
                    args[key] = int(args[key])
                except ValueError:
                    abort("{} must be an integer.".format(key))

        if (args['--owners'] is not None
                and not len(args['--owners'].split(',')) >= 2):
            abort('--owners must be >= 2')

        if args['encrypt'] or args['decrypt']:
            if args['--file'] is not None:
                try:
                    with open(args['--file']) as datafile:
                        args['--data'] = datafile.read()
                except IOError:
                    abort("couldn't open file {}".format(args['--file']))
            else:
                args['--data'] = args['--str']

        # get password
        args['--password'] = authenticate(args['--user'])

        # do stuff
        if args['create']:
            upload = json.dumps({
                'Name': args['--user'],
                'Password': args['--password'],
            })
            goodquit_json(api_call('create', args, upload))

        elif args['delegate']:
            upload = json.dumps({
                'Name': args['--user'],
                'Password': args['--password'],
                'Time': args['--time'],
                'Uses': args['--uses'],
            })
            goodquit_json(api_call('delegate', args, upload))

        elif args['encrypt']:
            upload = json.dumps({
                'Name': args['--user'],
                'Password': args['--password'],
                'Minimum': args['--min'],
                'Owners': args['--owners'].split(','),
                'Data': args['--data'],
            })
            goodquit_json(api_call('encrypt', args, upload))

        elif args['decrypt']:
            upload = json.dumps({
                'Name': args['--user'],
                'Password': args['--password'],
                'Data': args['--data'],
            })
            goodquit_json(api_call('decrypt', args, upload))

        elif args['summary']:
            upload = json.dumps({
                'Name': args['--user'],
                'Password': args['--password'],
            })
            goodquit_json(api_call('summary', args, upload))

        elif args['change-password']:
            args['newpass'] = getpass.getpass('New Password: ')
            upload = json.dumps({
                'Name': args['--user'],
                'Password': args['--password'],
                'NewPassword': args['newpass'],
            })
            goodquit_json(api_call('password', args, upload))

        elif args['modify']:
            upload = json.dumps({
                'Name': args['--user'],
                'Password': args['--password'],
                'Command': args['--action'],
                'ToModify': args['--target'],
            })
            goodquit_json(api_call('modify', args, upload))

    except KeyboardInterrupt:
        sys.stderr.write('okay bye\n')
        sys.exit(130)
